### ISSUE TITLE
1.0.1 版本调用getUserByCode无返回值

### ISSUE THREAD

**Issue by wadezha** [node-webot/co-wechat-oauth#10]
[#39](https://github.com/node-webot/wechat-oauth/issues/39) 我用的es6 co 的库，node 还未升级到 7版本以上，听你的建议使用了 1.0.1 版本，但 getUserByCode 调用时 无返回值，看了一下你的源码，好像 _getUser 方法都不是一个 generator 函数，可不可以帮我看一下什么问题，给个解决方案

**Comment by JacksonTian** [comment]
还有问题吗
我先 close 掉
