### ISSUE TITLE
应该使用 yield* 吧

### ISSUE THREAD

**Issue by tangxinfa** [node-webot/co-wechat-oauth#6]
像这里

    OAuth.prototype.getUser = function * (options) {
      if (typeof options !== 'object') {
        options = {
          openid: options
        };
      }
    
      var data = yield this.getToken(options.openid);

getUser 是一个 Generator 它调用另一个 Generator getToken 的时候应该使用 yield* 吧？

**Comment by JacksonTian** [comment]
co对这个并没有要求。都能正确处理。当然也是有区别的。。出错时，堆栈不一样。
